/// Named routes + their paths, kept in one place to avoid stringly-typed bugs.
abstract final class RouteNames {
  RouteNames._();

  static const String splash = 'splash';
  static const String language = 'language';
  static const String country = 'country';
  static const String onboarding = 'onboarding';
  static const String welcome = 'welcome';
  static const String emailAuth = 'emailAuth';
  static const String phoneAuth = 'phoneAuth';
  static const String otp = 'otp';
  static const String userType = 'userType';
  static const String home = 'home';
  static const String settings = 'settings';
  static const String profile = 'profile';
  static const String editProfile = 'editProfile';
  static const String changePassword = 'changePassword';
  static const String resumeAnalyzer = 'resumeAnalyzer';
  static const String jobMatching = 'jobMatching';
  static const String careerCoach = 'careerCoach';
  static const String jobs = 'jobs';
  static const String jobDetail = 'jobDetail';
  static const String applications = 'applications';
  static const String applicationDetail = 'applicationDetail';
  static const String cvBuilder = 'cvBuilder';
  static const String cvPreview = 'cvPreview';
  static const String interviewPrep = 'interviewPrep';
  static const String interviewHistory = 'interviewHistory';
  static const String interviewSessionDetail = 'interviewSessionDetail';
  static const String recommendations = 'recommendations';
  static const String employerHome = 'employerHome';
  static const String companyProfile = 'companyProfile';
  static const String editCompany = 'editCompany';
  static const String employerJobs = 'employerJobs';
  static const String createJob = 'createJob';
  static const String jobPreview = 'jobPreview';
  static const String employerJobDetail = 'employerJobDetail';
  static const String editJob = 'editJob';

  static const String splashPath = '/';
  static const String languagePath = '/language';
  static const String countryPath = '/country';
  static const String onboardingPath = '/onboarding';
  static const String welcomePath = '/welcome';
  static const String emailAuthPath = '/auth/email';
  static const String phoneAuthPath = '/auth/phone';
  static const String otpPath = '/auth/otp';
  static const String userTypePath = '/user-type';
  static const String homePath = '/home';
  static const String settingsPath = '/settings';
  static const String profilePath = '/settings/profile';
  static const String editProfilePath = '/settings/profile/edit';
  static const String changePasswordPath = '/settings/change-password';
  static const String resumeAnalyzerPath = '/resume-analyzer';
  static const String jobMatchingPath = '/job-matching';
  static const String careerCoachPath = '/career-coach';
  static const String jobsPath = '/jobs';
  static const String jobDetailPath = '/jobs/:id';
  static const String applicationsPath = '/applications';
  static const String applicationDetailPath = '/applications/:id';
  static const String cvBuilderPath = '/cv-builder';
  static const String cvPreviewPath = '/cv-builder/preview';
  static const String interviewPrepPath = '/interview-prep';
  static const String interviewHistoryPath = '/interview-prep/history';
  static const String interviewSessionDetailPath = '/interview-prep/history/:id';
  static const String recommendationsPath = '/recommendations';
  static const String employerHomePath = '/employer';
  static const String companyProfilePath = '/employer/company';
  static const String editCompanyPath = '/employer/company/edit';
  // Static paths ('new'/'preview') precede ':id' so they match first.
  static const String employerJobsPath = '/employer/jobs';
  static const String createJobPath = '/employer/jobs/new';
  static const String jobPreviewPath = '/employer/jobs/preview';
  static const String employerJobDetailPath = '/employer/jobs/:id';
  static const String editJobPath = '/employer/jobs/:id/edit';
}
