/// Who authored a chat turn, from the model's perspective.
enum AiRole {
  /// A message from the human user.
  user,

  /// A message generated by the model/assistant.
  model,
}

/// A single conversation turn passed to [AiService.streamChat].
///
/// A deliberately minimal, provider-neutral value type: feature code builds a
/// list of these and only the concrete [AiService] implementation knows how to
/// translate them into vendor content. No vendor types leak across the
/// interface.
class AiMessage {
  const AiMessage({required this.role, required this.text});

  const AiMessage.user(this.text) : role = AiRole.user;
  const AiMessage.model(this.text) : role = AiRole.model;

  final AiRole role;
  final String text;
}
