// File generated by FlutterFire CLI.
//
// Kept under core/services/firebase/ (the app's Firebase module) instead of
// the default lib/ root — firebase.json's dart output path points here, so
// re-running `flutterfire configure` regenerates this same file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2HjyOAHZ392uLX_NAl2WSUwu-HbV5sPQ',
    appId: '1:894890748117:web:1cb98aff4ccd2e26bd9a5c',
    messagingSenderId: '894890748117',
    projectId: 'careerbridge-97-f58c9',
    authDomain: 'careerbridge-97-f58c9.firebaseapp.com',
    storageBucket: 'careerbridge-97-f58c9.firebasestorage.app',
    measurementId: 'G-MHWW23NDF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnw3d7pLb1S1yz2tucfA4b_a1k55tF5tg',
    appId: '1:894890748117:android:ad64de25e2d10743bd9a5c',
    messagingSenderId: '894890748117',
    projectId: 'careerbridge-97-f58c9',
    storageBucket: 'careerbridge-97-f58c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhFyiU8ntB4Zq4Li4WIuxbIo-mAGsStM',
    appId: '1:894890748117:ios:53e4a8c20bfdb681bd9a5c',
    messagingSenderId: '894890748117',
    projectId: 'careerbridge-97-f58c9',
    storageBucket: 'careerbridge-97-f58c9.firebasestorage.app',
    iosBundleId: 'com.careerbridge.careerbridge',
  );
}
