import '../../shared/models/country_model.dart';

/// Static country dataset for the picker.
///
/// Emoji flags keep this asset-free. The list is easily extended to the full
/// ISO 3166 set — the picker, search, and persistence all operate on
/// [CountryModel] generically, so adding rows requires no code changes.
abstract final class CountriesData {
  CountriesData._();

  static const List<CountryModel> all = [
    CountryModel(isoCode: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦'),
    CountryModel(isoCode: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬'),
    CountryModel(isoCode: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦'),
    CountryModel(isoCode: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪'),
    CountryModel(isoCode: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼'),
    CountryModel(isoCode: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭'),
    CountryModel(isoCode: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲'),
    CountryModel(isoCode: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴'),
    CountryModel(isoCode: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧'),
    CountryModel(isoCode: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶'),
    CountryModel(isoCode: 'SY', name: 'Syria', dialCode: '+963', flag: '🇸🇾'),
    CountryModel(isoCode: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸'),
    CountryModel(isoCode: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪'),
    CountryModel(isoCode: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦'),
    CountryModel(isoCode: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿'),
    CountryModel(isoCode: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳'),
    CountryModel(isoCode: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾'),
    CountryModel(isoCode: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩'),
    CountryModel(isoCode: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸'),
    CountryModel(isoCode: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦'),
    CountryModel(isoCode: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧'),
    CountryModel(isoCode: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪'),
    CountryModel(isoCode: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷'),
    CountryModel(isoCode: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪'),
    CountryModel(isoCode: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸'),
    CountryModel(isoCode: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹'),
    CountryModel(isoCode: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹'),
    CountryModel(isoCode: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱'),
    CountryModel(isoCode: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪'),
    CountryModel(isoCode: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭'),
    CountryModel(isoCode: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹'),
    CountryModel(isoCode: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪'),
    CountryModel(isoCode: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴'),
    CountryModel(isoCode: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰'),
    CountryModel(isoCode: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮'),
    CountryModel(isoCode: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱'),
    CountryModel(isoCode: 'CZ', name: 'Czechia', dialCode: '+420', flag: '🇨🇿'),
    CountryModel(isoCode: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷'),
    CountryModel(isoCode: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴'),
    CountryModel(isoCode: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦'),
    CountryModel(isoCode: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺'),
    CountryModel(isoCode: 'TR', name: 'Türkiye', dialCode: '+90', flag: '🇹🇷'),
    CountryModel(isoCode: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷'),
    CountryModel(isoCode: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰'),
    CountryModel(isoCode: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳'),
    CountryModel(isoCode: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩'),
    CountryModel(isoCode: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰'),
    CountryModel(isoCode: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵'),
    CountryModel(isoCode: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳'),
    CountryModel(isoCode: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵'),
    CountryModel(isoCode: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷'),
    CountryModel(isoCode: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩'),
    CountryModel(isoCode: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾'),
    CountryModel(isoCode: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬'),
    CountryModel(isoCode: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭'),
    CountryModel(isoCode: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳'),
    CountryModel(isoCode: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭'),
    CountryModel(isoCode: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺'),
    CountryModel(isoCode: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿'),
    CountryModel(isoCode: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦'),
    CountryModel(isoCode: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬'),
    CountryModel(isoCode: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪'),
    CountryModel(isoCode: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹'),
    CountryModel(isoCode: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭'),
    CountryModel(isoCode: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿'),
    CountryModel(isoCode: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷'),
    CountryModel(isoCode: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷'),
    CountryModel(isoCode: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽'),
    CountryModel(isoCode: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱'),
    CountryModel(isoCode: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴'),
    CountryModel(isoCode: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪'),
  ];
}
